# Generated by Django 3.2.5 on 2021-09-09 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bindit_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bindit_id', models.PositiveIntegerField()),
                ('amount', models.CharField(max_length=128)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.account')),
            ],
        ),
    ]
